### ISSUE TITLE
lit-element v1 build

### ISSUE THREAD

**Issue by motss** [motss/app-datepicker#127]
## Checklist

- [x] To add focus management when datepicker opens. Applies to plain, backdrop, and modal dialogs.
- [x] To update keyboard support to not go beyond allowable (or disabled) date range.
- [x] To implement min, max, adjust _currentDate if min is smaller than value (selectedDate), hide or show chevrons according to the value of min and max, to disable scrolling in year list view if necessary.
- [x] To remove attribute format as native input[type=date] does not support it. Format of an input date is determined via locale of the browser, nor does it affect the output of the selected date. Worth noting that the value is always in the format yyyy-mm-dd.
- [ ] To improve support for screen readers.
- [ ] To implement showing tooltip when mouse hover the input type=date.

## Proposals
- [ ] To use HTMLInputElement's selectionStart and selectionEnd to highlight selectable year, month and day in native <input> element. tab-ing to focus next selectable items are possible!
- [ ] To allow stepUp and stepDown to manipulate input date via step attribute.
- [ ] To implement inline datepicker.
- [ ] To implement attribute step.
