### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by motss** [motss/app-datepicker#13]
- [x] Select year with keyboard at list view with `enter`, `arrow-up` and `arrow-down`
- [x] Auto focus on selected year at list view
- [x] Restore focus on list view closed.
- [x] Selectable dates are focusable with `tab`
- [x] Disabled days / grayed out dates are not selectable with keyboard at all.
- [x] Make dialog modal to trap all focus.
- [x] New accessibility guideline for datepicker: http://eureka2.github.io/ab-datepicker/
- [ ] ~~Imperatively changes focusable elements on different views.~~ (Not applicable)
- [x] ~~https://www.w3.org/TR/wai-aria-practices-1.1/#datepicker~~ (Link not found)

**Comment by rachelmrgls** [comment]
The year selection works great, as does increment and decrement month, and traversing through enabled days, but actually selecting the hovered day of the month isnt accessible. Is this a known problem?

**Comment by motss** [comment]
It should not be accessible in `v4` for all days of month. Closing this as of now.
