### ISSUE TITLE
To update app-datepicker according to latest behavior of datepicker in Android 10

### ISSUE THREAD

**Issue by motss** [motss/app-datepicker#161]
## TO-DO

* [x] When navigate between months by clicking on arrow buttons, the calendar no longer animates to swipe to left or right. The current calendar basically re-renders with new values.
* [x] To support dark theme based on system default with `prefer-color-sheme`.
* [x] The datepicker comes with a `CLEAR` button and `OK` button is now `SET` button (e511de5
)

**Comment by motss** [comment]
All resolved!
